pipeline {
    agent { docker { image 'maven:3.8.4-openjdk:8-jdk-alpine' } }
    stages {
        stage('build') {
            steps {
                sh 'mvn --version'
            }
        }
    }
}