pipeline {
    //agent any
    agent {
        docker {image 'spring-boot-docker:2'}
    }
    stages {
        stage('Build') {
            steps {
                bat 'set'
                echo 'Building'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying'
            }
        }
    }
    post {
            always {
                echo 'This will always run'
            }
            success {
                echo 'This will run only if successful'
                //mail to: 'patel.upchar@gmail.com',
                 //subject: "Success Pipeline: ${currentBuild.fullDisplayName}",
                 /*body: "Successful build for ${env.BUILD_URL}"*/
            }
            failure {
                echo 'This will run only if failed'
                mail to: 'patel.upchar@gmail.com',
                 subject: "Failed Pipeline: ${currentBuild.fullDisplayName}",
                 body: "Something is wrong with ${env.BUILD_URL}"
            }
            unstable {
                echo 'This will run only if the run was marked as unstable'
            }
            changed {
                echo 'This will run only if the state of the Pipeline has changed'
                echo 'For example, if the Pipeline was previously failing but is now successful'
            }
    }
}